version: '3.7'
services:
   db:
    image: mysql:5.6
    container_name: new-side-project-mysql
    ports:
      - "2107:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: test_db
    volumes:
      - ./volumes/mysql:/var/lib/mysql
